/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siscolab.telas;
import java.util.ArrayList;
import siscolab.modelos.Usuario;
import siscolab.telas.*;
import javax.swing.JFrame;
/**
 *
 * @author 20171BSI0278
 */
public class Inicio extends javax.swing.JFrame {
    private ArrayList<Usuario> containerUsuarios;
    MedicoListagem medicoListagem;
    PacienteInicio pacienteTelaInicio;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        this.containerUsuarios = new ArrayList();
        this.medicoListagem = new MedicoListagem();
        this.pacienteTelaInicio = new PacienteInicio();
        initComponents();
    }
    
    public Inicio(ArrayList container) {
        this.containerUsuarios = container;
        this.medicoListagem = new MedicoListagem(this.containerUsuarios);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        bMed = new javax.swing.JButton();
        bPac = new javax.swing.JButton();
        bLab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(115, 153, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SISCOLAB");

        text1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        text1.setText("Bem vindo ao");

        text2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        text2.setText("Sistema de Consulta de exames Laboratoriais");

        bMed.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        bMed.setText("Área do Médico");
        bMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMedActionPerformed(evt);
            }
        });

        bPac.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        bPac.setText("Área do Paciente");
        bPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPacActionPerformed(evt);
            }
        });

        bLab.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        bLab.setText("Área Laboratório");
        bLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(text1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(text2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(bLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPac)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(text2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPac)
                    .addComponent(bLab)
                    .addComponent(bMed))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLabActionPerformed

    private void bMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMedActionPerformed
        // TODO add your handling code here:
        
        this.medicoListagem.setVisible(true);
    }//GEN-LAST:event_bMedActionPerformed

    private void bPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPacActionPerformed
        this.pacienteTelaInicio.setVisible(true);
    }//GEN-LAST:event_bPacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLab;
    private javax.swing.JButton bMed;
    private javax.swing.JButton bPac;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
