/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siscolab.telas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import siscolab.modelos.*;
import javax.swing.*;
/**
 *
 * @author 20171BSI0278
 */
public class MedicoCadastro extends javax.swing.JFrame {

    private ArrayList<Usuario> container;
    /**
     * Creates new form MedicoCadastro
     */
    public MedicoCadastro() {
        container = new ArrayList();
        initComponents();
    }
    
    public MedicoCadastro(ArrayList container) {
        this.container = container;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        cpfT = new javax.swing.JLabel();
        cpfC = new javax.swing.JTextField();
        rgT = new javax.swing.JLabel();
        rgC = new javax.swing.JTextField();
        nomeT = new javax.swing.JLabel();
        nomeC = new javax.swing.JTextField();
        sobrenomeT = new javax.swing.JLabel();
        sobrenomeC = new javax.swing.JTextField();
        dataNascimentoT = new javax.swing.JLabel();
        dataNascimentoC = new javax.swing.JTextField();
        emailT = new javax.swing.JLabel();
        emailC = new javax.swing.JTextField();
        senhaT = new javax.swing.JLabel();
        senhaC = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        especialidadeT = new javax.swing.JLabel();
        especialidadeC = new javax.swing.JTextField();
        senhaT1 = new javax.swing.JLabel();
        municipioC = new javax.swing.JTextField();
        crmT = new javax.swing.JLabel();
        crmC = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(115, 153, 0));
        titulo.setText("SISCOLAB");

        cpfT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        cpfT.setText("CPF:");

        cpfC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        cpfC.setText("Insira o CPF");
        cpfC.setToolTipText("Insira o CPF");

        rgT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        rgT.setText("RG:");

        rgC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        rgC.setText("Insira o RG");
        rgC.setToolTipText("");
        rgC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgCActionPerformed(evt);
            }
        });

        nomeT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        nomeT.setText("Nome:");

        nomeC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        nomeC.setText("Insira o seu nome");
        nomeC.setToolTipText("");
        nomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCActionPerformed(evt);
            }
        });

        sobrenomeT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        sobrenomeT.setText("Sobrenome:");

        sobrenomeC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        sobrenomeC.setText("Insira o seu sobrenome");
        sobrenomeC.setToolTipText("");
        sobrenomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeCActionPerformed(evt);
            }
        });

        dataNascimentoT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        dataNascimentoT.setText("Data de Nascimento:");

        dataNascimentoC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        dataNascimentoC.setText("dd/mm/yyyy");
        dataNascimentoC.setToolTipText("");
        dataNascimentoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoCActionPerformed(evt);
            }
        });

        emailT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        emailT.setText("Email:");

        emailC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        emailC.setText("Insira o seu email");
        emailC.setToolTipText("");
        emailC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCActionPerformed(evt);
            }
        });

        senhaT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaT.setText("Senha:");

        senhaC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaC.setText("Insira a sua senha");
        senhaC.setToolTipText("");
        senhaC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        senhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCActionPerformed(evt);
            }
        });

        ok.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        ok.setText("OK");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        especialidadeT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        especialidadeT.setText("Especialidade:");

        especialidadeC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        especialidadeC.setText("Insira a sua especialidade");
        especialidadeC.setToolTipText("");
        especialidadeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeCActionPerformed(evt);
            }
        });

        senhaT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaT1.setText("Municipio: ");

        municipioC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        municipioC.setText("Insira o seu municipio");
        municipioC.setToolTipText("");
        municipioC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        municipioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioCActionPerformed(evt);
            }
        });

        crmT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        crmT.setText("CRM:");

        crmC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        crmC.setText("11111111");
        crmC.setToolTipText("");
        crmC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crmCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(cpfT)
                    .addComponent(rgT)
                    .addComponent(nomeT)
                    .addComponent(sobrenomeT)
                    .addComponent(dataNascimentoT)
                    .addComponent(emailT)
                    .addComponent(senhaT)
                    .addComponent(crmT)
                    .addComponent(especialidadeT)
                    .addComponent(senhaT1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(crmC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(especialidadeC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(municipioC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobrenomeC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rgC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfC, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dataNascimentoC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(ok)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfT)
                    .addComponent(cpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgT)
                    .addComponent(rgC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeT)
                    .addComponent(nomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenomeT)
                    .addComponent(sobrenomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoT)
                    .addComponent(dataNascimentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailT)
                    .addComponent(emailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaT)
                    .addComponent(senhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crmT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(especialidadeT)
                        .addGap(12, 12, 12)
                        .addComponent(senhaT1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crmC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especialidadeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(municipioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ok))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rgCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgCActionPerformed

    private void sobrenomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeCActionPerformed

    private void nomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCActionPerformed

    private void dataNascimentoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoCActionPerformed

    private void emailCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCActionPerformed

    private void senhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void especialidadeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeCActionPerformed

    private void municipioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioCActionPerformed

    private void crmCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crmCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crmCActionPerformed

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked

        // Lembrar de mudar para pegar de um banco/array de cadastro de especialidades...
        Especialidade e = new Especialidade(this.especialidadeC.getText());
        Date data;
        try{
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
            String dateInString = this.dataNascimentoC.getText();
            data = formatter.parse(dateInString);
        }catch(ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida!");
            return;
        }
        // String cpf, String rg, String nome, String sobrenome, Date dataNascimento, String email, String senha, String crm, Especialidade especialidade, String municipioAtuacao
        Medico m = new Medico(this.cpfC.getText(), this.rgC.getText(), this.nomeC.getText(), this.sobrenomeC.getText(), data, this.emailC.getText(), this.senhaC.getText(), this.crmC.getText(), e, this.municipioC.getText()); 
        this.container.add(m);
        JOptionPane.showMessageDialog(this, "Médico adicionado com sucesso!");
    }//GEN-LAST:event_okMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfC;
    private javax.swing.JLabel cpfT;
    private javax.swing.JTextField crmC;
    private javax.swing.JLabel crmT;
    private javax.swing.JTextField dataNascimentoC;
    private javax.swing.JLabel dataNascimentoT;
    private javax.swing.JTextField emailC;
    private javax.swing.JLabel emailT;
    private javax.swing.JTextField especialidadeC;
    private javax.swing.JLabel especialidadeT;
    private javax.swing.JTextField municipioC;
    private javax.swing.JTextField nomeC;
    private javax.swing.JLabel nomeT;
    private javax.swing.JButton ok;
    private javax.swing.JTextField rgC;
    private javax.swing.JLabel rgT;
    private javax.swing.JTextField senhaC;
    private javax.swing.JLabel senhaT;
    private javax.swing.JLabel senhaT1;
    private javax.swing.JTextField sobrenomeC;
    private javax.swing.JLabel sobrenomeT;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
