/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siscolab.telas;

import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import siscolab.modelos.Usuario;
//import siscolab.modelos.Validacao.SoNumeros;
import static siscolab.modelos.Validacao.convertDate;
import static siscolab.modelos.Validacao.validaCpf;
import static siscolab.modelos.Validacao.validaEmail;
import static siscolab.modelos.Validacao.validaNasc;
import static siscolab.modelos.Validacao.isNotEmpty;
import static siscolab.modelos.Validacao.validaRg;

/**
 *
 * @author Julia
 */
public class PacienteCadastro extends javax.swing.JFrame {

    private ArrayList<Usuario> container;

    /**
     * Creates new form PacienteCadastro
     */
    public PacienteCadastro() {
        container = new ArrayList();
        initComponents();
        
    }
    
    public PacienteCadastro(ArrayList container) {
        this.container = container;
        initComponents();
        
        //rgC.setDocument(new SoNumeros());

    }
    
    
    
    public JFormattedTextField getCpfC() {
        return cpfC;
    }

    public void setCpfC(String cpfC) {
        this.cpfC.setText(cpfC);
    }

    public JFormattedTextField getDataNascimentoC() {
        return dataNascimentoC;
    }

    public void setDataNascimentoC(String dataNascimentoC) {
        this.dataNascimentoC.setText(dataNascimentoC);
    }

    public JTextField getEmailC() {
        return numeroC;
    }

    public void setEmailC(String emailC) {
        this.numeroC.setText(emailC);
    }

    public JTextField getMunicipioC() {
        return municipioC;
    }

    public void setMunicipioC(String municipioC) {
        this.municipioC.setText(municipioC);
    }

    public JTextField getNomeC() {
        return nomeC;
    }

    public void setNomeC(String nomeC) {
        this.nomeC.setText(nomeC);
    }

    public JTextField getPlanoSaudeC() {
        return planoSaudeC;
    }

    public void setPlanoSaudeC(String planoSaudeC) {
        this.planoSaudeC.setText(planoSaudeC);
    }

    public JFormattedTextField getRgC() {
        return rgC;
    }

    public void setRgC(String rgC) {
        this.rgC.setText(rgC);
    }

    public JPasswordField getSenhaC() {
        return senhaC;
    }

    public void setSenhaC(String senhaC) {
        this.senhaC.setText(senhaC);
    }

    public JTextField getSobrenomeC() {
        return sobrenomeC;
    }

    public void setSobrenomeC(String sobrenomeC) {
        this.sobrenomeC.setText(sobrenomeC);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        cpfT = new javax.swing.JLabel();
        cpfC = new javax.swing.JFormattedTextField();
        rgT = new javax.swing.JLabel();
        rgC = new javax.swing.JFormattedTextField();
        nomeT = new javax.swing.JLabel();
        nomeC = new javax.swing.JTextField();
        sobrenomeT = new javax.swing.JLabel();
        sobrenomeC = new javax.swing.JTextField();
        numeroT = new javax.swing.JLabel();
        planoSaudeT = new javax.swing.JLabel();
        municipioT = new javax.swing.JLabel();
        dataNascimentoT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dataNascimentoC = new javax.swing.JFormattedTextField();
        municipioC = new javax.swing.JTextField();
        numeroC = new javax.swing.JTextField();
        planoSaudeC = new javax.swing.JTextField();
        bInserir = new javax.swing.JButton();
        senhaC = new javax.swing.JPasswordField();
        emailT = new javax.swing.JLabel();
        senhaT = new javax.swing.JLabel();
        emailC = new javax.swing.JTextField();
        dataValidT = new javax.swing.JLabel();
        dataValidC = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(115, 153, 0));
        titulo.setText("SISCOLAB - Área do paciente");

        cpfT.setText("CPF:");

        try {
            cpfC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCActionPerformed(evt);
            }
        });

        rgT.setText("RG:");

        rgC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        nomeT.setText("Nome:");

        nomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCActionPerformed(evt);
            }
        });

        sobrenomeT.setText("Sobrenome:");

        numeroT.setText("Numero do plano:");

        planoSaudeT.setText("Plano de Saúde:");

        municipioT.setText("Município:");

        dataNascimentoT.setText("Dt. de nascimento:");

        jLabel1.setText("- ES");

        try {
            dataNascimentoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoCActionPerformed(evt);
            }
        });

        municipioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioCActionPerformed(evt);
            }
        });

        numeroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCActionPerformed(evt);
            }
        });

        planoSaudeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planoSaudeCActionPerformed(evt);
            }
        });

        bInserir.setText("Inserir");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });

        emailT.setText("Email:");

        senhaT.setText("Senha:");

        emailC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCActionPerformed(evt);
            }
        });

        dataValidT.setText("Dt. de validade:");

        try {
            dataValidC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataValidC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataValidCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dataNascimentoT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimentoC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(municipioT)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfT)
                                    .addComponent(nomeT))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cpfC, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(nomeC))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sobrenomeT)
                                    .addComponent(rgT)))
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(municipioC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sobrenomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rgC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bInserir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(planoSaudeT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(planoSaudeC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(emailT)
                            .addGap(18, 18, 18)
                            .addComponent(emailC, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senhaT)
                            .addGap(18, 18, 18)
                            .addComponent(senhaC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(numeroT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(numeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(dataValidT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataValidC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfT)
                    .addComponent(cpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgT)
                    .addComponent(rgC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeT)
                    .addComponent(sobrenomeT)
                    .addComponent(sobrenomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoT)
                    .addComponent(dataNascimentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipioT)
                    .addComponent(municipioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planoSaudeT)
                    .addComponent(planoSaudeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroT)
                    .addComponent(numeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataValidT)
                        .addComponent(dataValidC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailT)
                    .addComponent(emailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaT)
                    .addComponent(senhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bInserir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCActionPerformed

    private void nomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCActionPerformed

    private void dataNascimentoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoCActionPerformed

    private void municipioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioCActionPerformed

    private void numeroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCActionPerformed

    private void planoSaudeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planoSaudeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planoSaudeCActionPerformed

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        boolean aux = true; //while existe exception
        boolean aux1 = true;
        boolean aux2 = true;
        boolean aux3 = true;
        
        if (isNotEmpty(cpfC.getText()) && isNotEmpty(rgC.getText())
                && isNotEmpty(nomeC.getText()) && isNotEmpty(sobrenomeC.getText()) && isNotEmpty(dataNascimentoC.getText())
                && isNotEmpty(municipioC.getText()) && isNotEmpty(planoSaudeC.getText()) 
                && isNotEmpty(numeroC.getText()) && isNotEmpty(senhaC.getText())){
            
            try{
                int[] dataA = new int[3];
                dataA = convertDate(dataNascimentoC.getText());
                validaNasc(dataA);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Data de nascimento inválida!", "Error", JOptionPane.ERROR_MESSAGE);
                aux = false;
            }

            try {
                validaEmail(numeroC.getText());
            }catch (Exception ex){    
                JOptionPane.showMessageDialog(null, "E-mail inválido!", "Error", JOptionPane.ERROR_MESSAGE);
                aux1 = false;
            }

            try {
                validaCpf(cpfC.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "CPF inválido!", "Error", JOptionPane.ERROR_MESSAGE);
                aux2 = false;
            }
            
            try {
                validaRg(rgC.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Rg inválido!", "Error", JOptionPane.ERROR_MESSAGE);
                aux2 = false;
            }
            

            //if (aux && aux1 && aux2){
               // Medico medico= new Medico(cpfC.getText(), rgC.getText(), nomeC.getText(), sobrenomeC.getText(), dataA, );
            //}
            
        }else{
            JOptionPane.showMessageDialog(null, "Algum campo está vazio!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        
        
    }//GEN-LAST:event_bInserirActionPerformed

    private void emailCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCActionPerformed

    private void dataValidCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataValidCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataValidCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInserir;
    private javax.swing.JFormattedTextField cpfC;
    private javax.swing.JLabel cpfT;
    private javax.swing.JFormattedTextField dataNascimentoC;
    private javax.swing.JLabel dataNascimentoT;
    private javax.swing.JFormattedTextField dataValidC;
    private javax.swing.JLabel dataValidT;
    private javax.swing.JTextField emailC;
    private javax.swing.JLabel emailT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField municipioC;
    private javax.swing.JLabel municipioT;
    private javax.swing.JTextField nomeC;
    private javax.swing.JLabel nomeT;
    private javax.swing.JTextField numeroC;
    private javax.swing.JLabel numeroT;
    private javax.swing.JTextField planoSaudeC;
    private javax.swing.JLabel planoSaudeT;
    private javax.swing.JFormattedTextField rgC;
    private javax.swing.JLabel rgT;
    private javax.swing.JPasswordField senhaC;
    private javax.swing.JLabel senhaT;
    private javax.swing.JTextField sobrenomeC;
    private javax.swing.JLabel sobrenomeT;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
