/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siscolab.telas;

/**
 *
 * @author 20171BSI0278
 */
public class PacienteTelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form PacienteTelaCadastro
     */
    public PacienteTelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataNascimentoT = new javax.swing.JLabel();
        municipioC = new javax.swing.JTextField();
        senhaC = new javax.swing.JTextField();
        PlanoSaudeT = new javax.swing.JLabel();
        rgC = new javax.swing.JTextField();
        dataNascimentoC = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        PlanoSaudeC = new javax.swing.JTextField();
        nomeT = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        numPlanoT = new javax.swing.JLabel();
        emailT = new javax.swing.JLabel();
        nomeC = new javax.swing.JTextField();
        cpfT = new javax.swing.JLabel();
        numPlanoC = new javax.swing.JTextField();
        emailC = new javax.swing.JTextField();
        sobrenomeT = new javax.swing.JLabel();
        cpfC = new javax.swing.JTextField();
        municipioT = new javax.swing.JLabel();
        senhaT = new javax.swing.JLabel();
        sobrenomeC = new javax.swing.JTextField();
        rgT = new javax.swing.JLabel();
        dataNascimentoT1 = new javax.swing.JLabel();
        municipioC1 = new javax.swing.JTextField();
        senhaC1 = new javax.swing.JTextField();
        PlanoSaudeT1 = new javax.swing.JLabel();
        rgC1 = new javax.swing.JTextField();
        dataNascimentoC1 = new javax.swing.JTextField();
        ok1 = new javax.swing.JButton();
        PlanoSaudeC1 = new javax.swing.JTextField();
        nomeT1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        numPlanoT1 = new javax.swing.JLabel();
        emailT1 = new javax.swing.JLabel();
        nomeC1 = new javax.swing.JTextField();
        cpfT1 = new javax.swing.JLabel();
        numPlanoC1 = new javax.swing.JTextField();
        emailC1 = new javax.swing.JTextField();
        sobrenomeT1 = new javax.swing.JLabel();
        cpfC1 = new javax.swing.JTextField();
        municipioT1 = new javax.swing.JLabel();
        senhaT1 = new javax.swing.JLabel();
        sobrenomeC1 = new javax.swing.JTextField();
        rgT1 = new javax.swing.JLabel();

        dataNascimentoT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        dataNascimentoT.setText("Data de Nascimento:");

        municipioC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        municipioC.setText("Insira o seu municipio");
        municipioC.setToolTipText("");
        municipioC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        municipioC.setFocusable(false);

        senhaC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaC.setText("Insira a sua senha");
        senhaC.setToolTipText("");
        senhaC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        PlanoSaudeT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        PlanoSaudeT.setText("Plano de Saúde");

        rgC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        rgC.setText("Insira o RG");
        rgC.setToolTipText("");

        dataNascimentoC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        dataNascimentoC.setText("dd/mm/yyyy");
        dataNascimentoC.setToolTipText("");

        ok.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        ok.setText("OK");

        PlanoSaudeC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        PlanoSaudeC.setText("Unimed");
        PlanoSaudeC.setToolTipText("");

        nomeT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        nomeT.setText("Nome:");

        titulo.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(115, 153, 0));
        titulo.setText("SISCOLAB");

        numPlanoT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        numPlanoT.setText("Número do plano:");

        emailT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        emailT.setText("Email:");

        nomeC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        nomeC.setText("Insira o seu nome");
        nomeC.setToolTipText("");

        cpfT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        cpfT.setText("CPF:");

        numPlanoC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        numPlanoC.setText("1111111111");
        numPlanoC.setToolTipText("");

        emailC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        emailC.setText("Insira o seu email");
        emailC.setToolTipText("");

        sobrenomeT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        sobrenomeT.setText("Sobrenome:");

        cpfC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        cpfC.setText("Insira o CPF");
        cpfC.setToolTipText("Insira o CPF");

        municipioT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        municipioT.setText("Municipio de residência: ");

        senhaT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaT.setText("Senha:");

        sobrenomeC.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        sobrenomeC.setText("Insira o seu sobrenome");
        sobrenomeC.setToolTipText("");

        rgT.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        rgT.setText("RG:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataNascimentoT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        dataNascimentoT1.setText("Data de Nascimento:");

        municipioC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        municipioC1.setText("Insira o seu municipio");
        municipioC1.setToolTipText("");
        municipioC1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        municipioC1.setFocusable(false);
        municipioC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioC1ActionPerformed(evt);
            }
        });

        senhaC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaC1.setText("Insira a sua senha");
        senhaC1.setToolTipText("");
        senhaC1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        senhaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaC1ActionPerformed(evt);
            }
        });

        PlanoSaudeT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        PlanoSaudeT1.setText("Plano de Saúde");

        rgC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        rgC1.setText("Insira o RG");
        rgC1.setToolTipText("");

        dataNascimentoC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        dataNascimentoC1.setText("dd/mm/yyyy");
        dataNascimentoC1.setToolTipText("");
        dataNascimentoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoC1ActionPerformed(evt);
            }
        });

        ok1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        ok1.setText("OK");

        PlanoSaudeC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        PlanoSaudeC1.setText("Insira o seu plano de saúde");
        PlanoSaudeC1.setToolTipText("");
        PlanoSaudeC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanoSaudeC1ActionPerformed(evt);
            }
        });

        nomeT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        nomeT1.setText("Nome:");

        titulo1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        titulo1.setForeground(new java.awt.Color(115, 153, 0));
        titulo1.setText("SISCOLAB");

        numPlanoT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        numPlanoT1.setText("Número do plano:");

        emailT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        emailT1.setText("Email:");

        nomeC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        nomeC1.setText("Insira o seu nome");
        nomeC1.setToolTipText("");

        cpfT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        cpfT1.setText("CPF:");

        numPlanoC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        numPlanoC1.setText("1111111111");
        numPlanoC1.setToolTipText("");

        emailC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        emailC1.setText("Insira o seu email");
        emailC1.setToolTipText("");

        sobrenomeT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        sobrenomeT1.setText("Sobrenome:");

        cpfC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        cpfC1.setText("Insira o CPF");
        cpfC1.setToolTipText("Insira o CPF");

        municipioT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        municipioT1.setText("Municipio:");

        senhaT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        senhaT1.setText("Senha:");

        sobrenomeC1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        sobrenomeC1.setText("Insira o seu sobrenome");
        sobrenomeC1.setToolTipText("");

        rgT1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        rgT1.setText("RG:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlanoSaudeT1)
                            .addComponent(numPlanoT1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(municipioT1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(municipioC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataNascimentoT1)
                                .addComponent(titulo1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rgT1)
                                        .addComponent(nomeT1)
                                        .addComponent(sobrenomeT1)
                                        .addComponent(emailT1)
                                        .addComponent(senhaT1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(56, 56, 56)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nomeC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(sobrenomeC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rgC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cpfC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(PlanoSaudeC1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                .addComponent(dataNascimentoC1)
                                                .addComponent(emailC1)
                                                .addComponent(senhaC1)
                                                .addComponent(numPlanoC1)))))
                                .addComponent(cpfT1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(ok1)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfT1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cpfC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgT1)
                    .addComponent(rgC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeT1)
                    .addComponent(nomeC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenomeT1)
                    .addComponent(sobrenomeC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoT1)
                    .addComponent(dataNascimentoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailT1)
                    .addComponent(emailC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaT1)
                    .addComponent(senhaC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlanoSaudeT1)
                    .addComponent(PlanoSaudeC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPlanoT1)
                    .addComponent(numPlanoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipioT1)
                    .addComponent(municipioC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataNascimentoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoC1ActionPerformed

    private void senhaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaC1ActionPerformed

    private void PlanoSaudeC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanoSaudeC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlanoSaudeC1ActionPerformed

    private void municipioC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteTelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PlanoSaudeC;
    private javax.swing.JTextField PlanoSaudeC1;
    private javax.swing.JLabel PlanoSaudeT;
    private javax.swing.JLabel PlanoSaudeT1;
    private javax.swing.JTextField cpfC;
    private javax.swing.JTextField cpfC1;
    private javax.swing.JLabel cpfT;
    private javax.swing.JLabel cpfT1;
    private javax.swing.JTextField dataNascimentoC;
    private javax.swing.JTextField dataNascimentoC1;
    private javax.swing.JLabel dataNascimentoT;
    private javax.swing.JLabel dataNascimentoT1;
    private javax.swing.JTextField emailC;
    private javax.swing.JTextField emailC1;
    private javax.swing.JLabel emailT;
    private javax.swing.JLabel emailT1;
    private javax.swing.JTextField municipioC;
    private javax.swing.JTextField municipioC1;
    private javax.swing.JLabel municipioT;
    private javax.swing.JLabel municipioT1;
    private javax.swing.JTextField nomeC;
    private javax.swing.JTextField nomeC1;
    private javax.swing.JLabel nomeT;
    private javax.swing.JLabel nomeT1;
    private javax.swing.JTextField numPlanoC;
    private javax.swing.JTextField numPlanoC1;
    private javax.swing.JLabel numPlanoT;
    private javax.swing.JLabel numPlanoT1;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    private javax.swing.JTextField rgC;
    private javax.swing.JTextField rgC1;
    private javax.swing.JLabel rgT;
    private javax.swing.JLabel rgT1;
    private javax.swing.JTextField senhaC;
    private javax.swing.JTextField senhaC1;
    private javax.swing.JLabel senhaT;
    private javax.swing.JLabel senhaT1;
    private javax.swing.JTextField sobrenomeC;
    private javax.swing.JTextField sobrenomeC1;
    private javax.swing.JLabel sobrenomeT;
    private javax.swing.JLabel sobrenomeT1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
